In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<img src="/Users/desiredewaele/Google Drive/Datasets/Leaves/images/11.jpg">

In [18]:
path = '/Users/desiredewaele/Google Drive/Datasets/Leaves/'
train = pd.read_csv(path + 'train.csv', index_col=0)
test = pd.read_csv(path + 'test.csv', index_col=0)
train.head()

,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
id,,,,,,,,,,,,,,,,,,,,,
1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,0.001953,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,0.000000,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,0.000000,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,0.013672,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,0.000000,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [11]:
train = train.sample(frac=1)
label = train.pop('species')

In [12]:
train = train / np.linalg.norm(train, axis=0)
test = test / np.linalg.norm(test, axis=0)
train.head()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
id,,,,,,,,,,,,,,,,,,,,,
793,0.007077,0.002576,0.007549,0.028738,0.088046,0.000000,0.009556,0.000000,0.027110,0.010090,...,0.000000,0.017109,0.000000,0.077653,0.061419,0.0,0.000000,0.045871,0.028290,0.000000
745,0.082564,0.052808,0.019626,0.000000,0.000000,0.052726,0.000000,0.000000,0.032531,0.042886,...,0.000849,0.017109,0.004410,0.004501,0.005583,0.0,0.026481,0.045165,0.005659,0.076773
960,0.000000,0.000000,0.003019,0.016905,0.138736,0.000000,0.000000,0.084232,0.081327,0.002523,...,0.002971,0.000000,0.103632,0.000000,0.001396,0.0,0.000000,0.007057,0.000000,0.009337
896,0.007077,0.003864,0.009058,0.013524,0.013341,0.004793,0.054952,0.000000,0.016264,0.045409,...,0.000000,0.000000,0.006614,0.002251,0.030709,0.0,0.000000,0.000706,0.054694,0.018674
231,0.068411,0.018032,0.016606,0.010143,0.002668,0.044099,0.038227,0.000000,0.010843,0.055500,...,0.075118,0.000000,0.004410,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.006224

In [15]:
split = int(len(train)*0.9)
trainX = train.iloc[:split]
validX = train.iloc[split:]
trainY = label.iloc[:split]
validY = label.iloc[split:]